// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package row

import (
	"fmt"
	"testing"

	fory "github.com/apache/fory/go/fory"
	"github.com/stretchr/testify/require"
)

// Golden bytes and hashes generated by Java
// org.apache.fory.format.type.SchemaEncoder (SCHEMA_VERSION=1) and
// DataTypes.computeSchemaHash. Regenerate with those classes if the
// Java wire format ever changes; the Java<->Go cross-language test is
// the live guard.
var schemaGoldens = []struct {
	name   string
	schema func() *Schema
	bytes  []byte
	hash   int64
}{
	{
		name: "simple",
		schema: func() *Schema {
			return NewSchema([]Field{
				NewField("id", Int32Type{}, true),
				NewField("name", StringType{}, true),
				NewField("score", Float64Type{}, true),
				NewField("active", BoolType{}, true),
			})
		},
		bytes: []byte{
			0x01, 0x04, 0x45, 0xa0, 0x60, 0x04, 0x49, 0x34, 0x0c, 0x20, 0x15, 0x4d,
			0xc8, 0x4e, 0x89, 0x00, 0x14, 0x4d, 0x00, 0x53, 0x45, 0x48, 0x01,
		},
		hash: 15839823,
	},
	{
		name: "nested",
		schema: func() *Schema {
			return NewSchema([]Field{
				NewField("person", Struct([]Field{
					NewField("name", StringType{}, true),
					NewField("age", Int32Type{}, false),
				}), true),
				NewField("tags", List(StringType{}), true),
				NewField("attrs", Map(StringType{}, Int64Type{}), true),
			})
		},
		bytes: []byte{
			0x01, 0x03, 0x4d, 0x3c, 0x91, 0x93, 0x9a, 0x1b, 0x02, 0x49, 0x34, 0x0c,
			0x20, 0x15, 0x05, 0x00, 0xc4, 0x04, 0x49, 0x4c, 0x06, 0x90, 0x16, 0x49,
			0x22, 0x64, 0x60, 0x15, 0x4d, 0x82, 0x73, 0x8c, 0x80, 0x18, 0x05, 0x28,
			0x98, 0x15, 0x4d, 0xd4, 0x0b, 0xa1, 0x00, 0x06,
		},
		hash: 15260761278193,
	},
	{
		name: "special",
		schema: func() *Schema {
			return NewSchema([]Field{
				NewField("a_very_long_field_name_exceeding_limit", Int64Type{}, false),
				NewField("field2", StringType{}, true),
				NewField("$special_name", Date32Type{}, true),
				NewField("CamelCase", TimestampType{}, false),
				NewField("price", DecimalType{Precision: 10, Scale: 2}, true),
			})
		},
		bytes: []byte{
			0x01, 0x05, 0x3d, 0x09, 0x03, 0x75, 0x24, 0x71, 0xb5, 0xb9, 0xa6, 0xd9,
			0x50, 0x45, 0x8f, 0x6d, 0x03, 0x09, 0xb2, 0x5c, 0x44, 0x20, 0xd0, 0xd3,
			0x6d, 0x68, 0x62, 0x26, 0x06, 0x52, 0x0a, 0x40, 0x85, 0x87, 0xb0, 0x15,
			0x61, 0xf2, 0x4f, 0x20, 0x90, 0x05, 0xed, 0xa0, 0x61, 0x00, 0x27, 0x1a,
			0x38, 0x01, 0x82, 0x16, 0xe0, 0x09, 0x08, 0x26, 0x4d, 0xbe, 0x28, 0x11,
			0x00, 0x28, 0x0a, 0x02,
		},
		hash: 492901001,
	},
}

func TestSchemaBytesGolden(t *testing.T) {
	for _, g := range schemaGoldens {
		schema := g.schema()

		got, err := SchemaToBytes(schema)
		require.NoError(t, err, g.name)
		require.Equal(t, g.bytes, got, "%s: bytes must match Java SchemaEncoder output", g.name)

		parsed, err := SchemaFromBytes(g.bytes)
		require.NoError(t, err, g.name)
		require.True(t, parsed.Equal(schema), "%s: parsed schema %v != %v", g.name, parsed, schema)
	}
}

func TestSchemaHashGolden(t *testing.T) {
	for _, g := range schemaGoldens {
		require.Equal(t, g.hash, ComputeSchemaHash(g.schema()), g.name)
	}

	// 20 int64 fields overflow the int64 hash, exercising Java's
	// shift-right-2-and-retry path.
	fields := make([]Field, 20)
	for i := range fields {
		fields[i] = NewField(fmt.Sprintf("f%d", i), Int64Type{}, true)
	}
	require.Equal(t, int64(2627256684647412568), ComputeSchemaHash(NewSchema(fields)))
}

func requireErrorContains(t *testing.T, err error, substr string) {
	t.Helper()
	require.Error(t, err)
	require.Contains(t, err.Error(), substr)
}

func TestSchemaFromBytesErrors(t *testing.T) {
	// Unsupported version.
	_, err := SchemaFromBytes([]byte{0x02, 0x00})
	requireErrorContains(t, err, "schema version")

	// Invalid field name encoding index (bits 0-1 == 3).
	_, err = SchemaFromBytes([]byte{0x01, 0x01, 0x07})
	requireErrorContains(t, err, "encoding index")

	// Unknown type id.
	corrupt := append([]byte(nil), schemaGoldens[0].bytes...)
	corrupt[len(corrupt)-1] = 0x63
	_, err = SchemaFromBytes(corrupt)
	requireErrorContains(t, err, "unknown type id")

	// Field count larger than the remaining input.
	_, err = SchemaFromBytes([]byte{0x01, 0x7f})
	requireErrorContains(t, err, "fields")

	// Every strict prefix of a valid encoding must fail, never panic.
	golden := schemaGoldens[1].bytes
	for i := 0; i < len(golden); i++ {
		_, err := SchemaFromBytes(golden[:i])
		require.Error(t, err, "prefix of length %d", i)
	}
}

func TestSchemaToBytesRejectsEmptyName(t *testing.T) {
	_, err := SchemaToBytes(NewSchema([]Field{NewField("", Int32Type{}, true)}))
	requireErrorContains(t, err, "empty name")
}

// A crafted chain of nested LIST type-infos costs ~3 bytes per level;
// without a depth limit it would fatally overflow the goroutine stack.
func TestSchemaFromBytesRejectsDeepNesting(t *testing.T) {
	data := []byte{0x01, 0x01}
	for i := 0; i < 10*maxSchemaNestingDepth; i++ {
		// field: header (UTF_8 encoding, 1-byte name, non-null),
		// name "a", type LIST -> recurses into the next field.
		data = append(data, 0x00, 'a', 0x16)
	}
	_, err := SchemaFromBytes(data)
	requireErrorContains(t, err, "nesting")
}

type unknownDataType struct{}

func (unknownDataType) TypeID() fory.TypeId { return 99 }
func (unknownDataType) ByteWidth() int      { return -1 }
func (unknownDataType) String() string      { return "unknown" }

// The writer validates everything the wire format cannot express
// before emitting a byte, so its output is always readable.
func TestSchemaToBytesRejectsUnwritableSchemas(t *testing.T) {
	_, err := SchemaToBytes(nil)
	require.Error(t, err)

	// One level deeper than the reader accepts.
	var deep DataType = Int32Type{}
	for i := 0; i < maxSchemaNestingDepth; i++ {
		deep = List(deep)
	}
	_, err = SchemaToBytes(NewSchema([]Field{NewField("deep", deep, true)}))
	requireErrorContains(t, err, "nesting")
	// Exactly the reader's limit still round-trips.
	var ok DataType = Int32Type{}
	for i := 0; i < maxSchemaNestingDepth-1; i++ {
		ok = List(ok)
	}
	okBytes, err := SchemaToBytes(NewSchema([]Field{NewField("ok", ok, true)}))
	require.NoError(t, err)
	_, err = SchemaFromBytes(okBytes)
	require.NoError(t, err)

	// A type that refers to itself.
	loop := &ListType{}
	loop.Elem = NewField("item", loop, true)
	_, err = SchemaToBytes(NewSchema([]Field{NewField("loop", loop, true)}))
	requireErrorContains(t, err, "refers to itself")

	// Decimal parameters wider than the single wire byte.
	_, err = SchemaToBytes(NewSchema([]Field{NewField("d", DecimalType{Precision: 300, Scale: 2}, true)}))
	requireErrorContains(t, err, "decimal")

	// Pointer decimal and foreign DataType implementations.
	_, err = SchemaToBytes(NewSchema([]Field{NewField("d", &DecimalType{Precision: 10, Scale: 2}, true)}))
	require.Error(t, err)
	_, err = SchemaToBytes(NewSchema([]Field{NewField("u", unknownDataType{}, true)}))
	require.Error(t, err)
}
