# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements. See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0.

foryVersion=1.7.0-SNAPSHOT
kotlinVersion=2.3.20
kspVersion=2.3.8
kotlinxSerializationVersion=1.11.0
moshiVersion=1.15.2
jacksonVersion=2.22.1
jmhVersion=1.37
jmhPluginVersion=0.7.3
gradleVersion=9.3.0
org.gradle.caching=true
org.gradle.jvmargs=-Xmx2g
