// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

package evolving2;

option evolving = false;

message EvolvingMessage [id=1000, evolving=true] {
    int32 id = 1;
    string name = 2;
    string city = 3;
    optional string email = 4;
}

message FixedMessage [id=1001, evolving=false] {
    int32 id = 1;
    string name = 2;
    optional string email = 4;
}

message EvolvingSizeMessage [id=1002, evolving=true] {
    string payload = 1;
}

message FixedSizeMessage [id=1003, evolving=false] {
    string payload = 1;
}
