/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.fory.json.kotlin.ksp

internal object CompanionSourceWriter {
  fun write(model: JsonModel): String =
    buildString(16_384) {
      append("// Generated by Apache Fory. Do not edit.\n")
      if (model.packageName.isNotEmpty()) append("package ${model.packageName};\n\n")
      model.valueClass?.let {
        appendValueClass(model, it)
        return@buildString
      }
      append("public final class ${model.companionSimpleName}\n")
      append(
        "    extends org.apache.fory.json.codec.GeneratedJsonCodec<${model.targetSourceName}> {\n"
      )
      append("  public ${model.companionSimpleName}() {}\n\n")
      append("  @Override\n")
      append("  public Class<${model.targetSourceName}> type() {\n")
      append("    return ${model.targetSourceName}.class;\n")
      append("  }\n\n")
      append("  @Override\n")
      append("  public org.apache.fory.json.meta.JsonFieldAccessor[] fieldAccessors() {\n")
      append("    return new org.apache.fory.json.meta.JsonFieldAccessor[] {")
      model.members.indices.joinTo(this, ", ") { "new Accessor$it()" }
      append("};\n")
      append("  }\n\n")
      model.anySetter?.let { appendAnySetter(model, it) }
      model.creator?.let { appendCreator(model, it) }
      if (model.singleton) {
        append("  @Override\n")
        append("  public Object fixedInstance() {\n")
        append("    return ${model.operationSimpleName}.instance();\n")
        append("  }\n\n")
      }
      if (model.validators.isNotEmpty()) appendValidators(model)
      if (model.members.isNotEmpty() || model.anySetter != null) appendReflectionHelpers()
      model.members.forEachIndexed { index, member -> appendAccessor(model, index, member) }
      append("}\n")
    }

  private fun StringBuilder.appendValueClass(
    model: JsonModel,
    operations: ValueClassOperations,
  ) {
    val terminal = operations.terminalType
    val terminalParameter = if (terminal.primitive) terminal.sourceName else "Object"
    val terminalInput = if (terminal.primitive) "value" else terminal.argumentExpression("value")
    val operationType = valueOperationType(terminal)
    val operationName = valueOperationName(terminal)
    append("public final class ${model.companionSimpleName}\n")
    append("    extends org.apache.fory.json.kotlin.KotlinGeneratedValueClassCodec<")
    append("${model.targetSourceName}>\n")
    append("    implements org.apache.fory.json.kotlin.$operationType<")
    append("${model.targetSourceName}> {\n")
    append("  private static final org.apache.fory.json.kotlin.KotlinUnboxedValueClassOperations\n")
    append("      UNBOXED_OPERATIONS = new UnboxedOperations();\n")
    operations.layers.forEachIndexed { index, layer ->
      append("  private static final int VALUE_BYTES_$index =\n")
      append("      org.apache.fory.serializer.GraphMemoryEstimates.shallowObjectBytes(")
      append("${sourceName(layer.ownerBinaryName)}.class);\n")
    }
    append('\n')
    append("  public ${model.companionSimpleName}() {}\n\n")
    append("  @Override\n")
    append("  public Class<${model.targetSourceName}> type() {\n")
    append("    return ${model.targetSourceName}.class;\n")
    append("  }\n\n")
    append("  @Override\n")
    append("  protected org.apache.fory.json.kotlin.KotlinValueClassShape valueClassShape(\n")
    append("      org.apache.fory.reflect.TypeRef<?> type) {\n")
    append("    return new org.apache.fory.json.kotlin.KotlinValueClassShape(\n")
    append("        type,\n")
    append("        type.getTypeExtMeta() != null && type.getTypeExtMeta().nullable(),\n")
    append("        java.util.Arrays.asList(\n")
    operations.layers.forEachIndexed { index, layer ->
      append("            new org.apache.fory.json.kotlin.KotlinValueClassLayer(\n")
      append("                ${layer.occurrenceTypeExpression},\n")
      append("                ${sourceName(layer.ownerBinaryName)}.class,\n")
      append("                ${layer.underlyingTypeExpression},\n")
      append("                ${layer.carrierType.classLiteral},\n")
      append(
        "                \"${escapeJava(methodDescriptor(listOf(layer.carrierType), layer.carrierType.descriptor))}\",\n"
      )
      append(
        "                \"${escapeJava(methodDescriptor(listOf(layer.carrierType), classDescriptor(layer.ownerBinaryName)))}\",\n"
      )
      append(
        "                \"${escapeJava(methodDescriptor(emptyList(), layer.carrierType.descriptor))}\")"
      )
      if (index != operations.layers.lastIndex) append(',')
      append('\n')
    }
    append("        ),\n")
    append("        ${operations.terminalTypeExpression});\n")
    append("  }\n\n")
    append("  @Override\n")
    append("  public org.apache.fory.json.kotlin.KotlinUnboxedValueClassOperations ")
    append("unboxedOperations() {\n")
    append("    return UNBOXED_OPERATIONS;\n")
    append("  }\n\n")
    append("  @Override\n")
    append("  public ${model.targetSourceName} construct$operationName(\n")
    append("      org.apache.fory.json.reader.JsonReader reader, $terminalParameter value) {\n")
    appendConstruct(model, operations, terminalInput, true, true, "    ")
    append("  }\n\n")
    append("  @Override\n")
    append("  public ${model.targetSourceName} construct${operationName}Uncharged(")
    append("$terminalParameter value) {\n")
    appendConstruct(model, operations, terminalInput, false, true, "    ")
    append("  }\n\n")
    append("  @Override\n")
    append("  public $terminalParameter unbox$operationName(")
    append("${model.targetSourceName} value) {\n")
    appendExtract(model, operations, "value", "    ", false)
    append("  }\n\n")
    appendUnboxedOperations(model, operations)
    appendDeclaredMethod()
    append("}\n")
  }

  private fun StringBuilder.appendConstruct(
    model: JsonModel,
    operations: ValueClassOperations,
    input: String,
    charged: Boolean,
    boxOuter: Boolean,
    indent: String,
  ) {
    var expression = adapt(input, operations.terminalType, operations.layers.last().carrierType)
    var current = operations.layers.last().carrierType
    for (index in operations.layers.indices.reversed()) {
      val layer = operations.layers[index]
      if (index != operations.layers.lastIndex) {
        val inner = operations.layers[index + 1]
        if (current.descriptor == classDescriptor(inner.ownerBinaryName)) {
          if (charged) append("${indent}reader.reserveGraphMemory(VALUE_BYTES_${index + 1});\n")
          val name = "boxed_${index + 1}"
          append("$indent${sourceName(inner.ownerBinaryName)} $name = ")
          append("${model.operationSimpleName}.valueBox_${index + 1}($expression);\n")
          expression = name
          current = JvmType(classDescriptor(inner.ownerBinaryName))
        }
      }
      require(current == layer.carrierType) {
        "Generated value-class carrier mismatch for ${layer.ownerBinaryName}"
      }
      val name = "carrier_$index"
      append("$indent${layer.carrierType.sourceName} $name = ")
      append("${model.operationSimpleName}.valueConstruct_$index($expression);\n")
      expression = name
      current = layer.carrierType
    }
    if (boxOuter) {
      if (charged) append("${indent}reader.reserveGraphMemory(VALUE_BYTES_0);\n")
      append("${indent}return ${model.operationSimpleName}.valueBox_0($expression);\n")
    } else {
      append("${indent}return $expression;\n")
    }
  }

  private fun StringBuilder.appendExtract(
    model: JsonModel,
    operations: ValueClassOperations,
    input: String,
    indent: String,
    boxedInput: Boolean,
  ) {
    val outer = operations.layers.first()
    var expression: String
    var current: JvmType
    if (boxedInput) {
      expression = outer.carrierType.argumentExpression(input)
      current = outer.carrierType
    } else {
      val name = "carrier_0"
      append("$indent${outer.carrierType.sourceName} $name = ")
      append("${model.operationSimpleName}.valueUnbox_0($input);\n")
      expression = name
      current = outer.carrierType
    }
    for (index in 1 until operations.layers.size) {
      val layer = operations.layers[index]
      if (current.descriptor == classDescriptor(layer.ownerBinaryName)) {
        val name = "carrier_$index"
        append("$indent${layer.carrierType.sourceName} $name = ")
        append("${model.operationSimpleName}.valueUnbox_$index($expression);\n")
        expression = name
        current = layer.carrierType
      } else {
        require(current == layer.carrierType) {
          "Generated value-class carrier mismatch for ${layer.ownerBinaryName}"
        }
      }
    }
    require(current == operations.terminalType) {
      "Generated value-class terminal carrier mismatch"
    }
    append("${indent}return $expression;\n")
  }

  private fun StringBuilder.appendUnboxedOperations(
    model: JsonModel,
    operations: ValueClassOperations,
  ) {
    val outer = operations.layers.first()
    append("  private static final class UnboxedOperations\n")
    append("      implements org.apache.fory.json.kotlin.KotlinUnboxedValueClassOperations {\n")
    append("    @Override\n")
    append("    public Object constructCarrier(\n")
    append("        org.apache.fory.json.reader.JsonReader reader, Object value) {\n")
    appendConstruct(
      model,
      operations,
      operations.terminalType.argumentExpression("value"),
      true,
      false,
      "      ",
    )
    append("    }\n\n")
    append("    @Override\n")
    append("    public Object extractValue(Object carrier) {\n")
    appendExtract(model, operations, "carrier", "      ", true)
    append("    }\n\n")
    append("    @Override\n")
    append("    public Object boxCarrier(Object carrier) {\n")
    append("      return ${model.operationSimpleName}.valueBox_0(")
    append("${outer.carrierType.argumentExpression("carrier")});\n")
    append("    }\n\n")
    append("    @Override\n")
    append("    public Object unboxValue(Object value) {\n")
    append("      return ${model.operationSimpleName}.valueUnbox_0(")
    append("(${model.targetSourceName}) value);\n")
    append("    }\n\n")
    append("    @Override\n")
    append("    public java.lang.reflect.Method[] constructMethods() {\n")
    append("      return new java.lang.reflect.Method[] {")
    constructMethodExpressions(operations).joinTo(this, ", ") { it.first }
    append("};\n")
    append("    }\n\n")
    append("    @Override\n")
    append("    public int[] constructBoxBytes() {\n")
    append("      return new int[] {")
    constructMethodExpressions(operations).joinTo(this, ", ") { it.second }
    append("};\n")
    append("    }\n\n")
    append("    @Override\n")
    append("    public java.lang.reflect.Method[] extractMethods() {\n")
    append("      return new java.lang.reflect.Method[] {")
    extractMethodExpressions(operations).joinTo(this, ", ")
    append("};\n")
    append("    }\n\n")
    append("    @Override\n")
    append("    public java.lang.reflect.Method boxMethod() {\n")
    append("      return ${boxMethodExpression(operations.layers.first())};\n")
    append("    }\n\n")
    append("    @Override\n")
    append("    public java.lang.reflect.Method unboxMethod() {\n")
    append("      return ${unboxMethodExpression(operations.layers.first())};\n")
    append("    }\n\n")
    append("    @Override\n")
    append("    public int boxBytes() {\n")
    append("      return VALUE_BYTES_0;\n")
    append("    }\n")
    append("  }\n\n")
  }

  private fun constructMethodExpressions(
    operations: ValueClassOperations,
  ): List<Pair<String, String>> = buildList {
    for (index in operations.layers.indices.reversed()) {
      val layer = operations.layers[index]
      add(constructorMethodExpression(layer) to "0")
      if (index > 0) {
        val outer = operations.layers[index - 1]
        if (outer.carrierType.descriptor == classDescriptor(layer.ownerBinaryName)) {
          add(boxMethodExpression(layer) to "VALUE_BYTES_$index")
        }
      }
    }
  }

  private fun extractMethodExpressions(operations: ValueClassOperations): List<String> = buildList {
    for (index in 1 until operations.layers.size) {
      val layer = operations.layers[index]
      if (
        operations.layers[index - 1].carrierType.descriptor ==
          classDescriptor(layer.ownerBinaryName)
      ) {
        add(unboxMethodExpression(layer))
      }
    }
  }

  private fun constructorMethodExpression(layer: ValueClassLayer): String =
    "declaredMethod(${sourceName(layer.ownerBinaryName)}.class, \"${escapeJava(layer.constructorName)}\", ${layer.carrierType.classLiteral})"

  private fun boxMethodExpression(layer: ValueClassLayer): String =
    "declaredMethod(${sourceName(layer.ownerBinaryName)}.class, \"${escapeJava(layer.boxName)}\", ${layer.carrierType.classLiteral})"

  private fun unboxMethodExpression(layer: ValueClassLayer): String =
    "declaredMethod(${sourceName(layer.ownerBinaryName)}.class, \"${escapeJava(layer.unboxName)}\")"

  private fun StringBuilder.appendDeclaredMethod() {
    append("  private static java.lang.reflect.Method declaredMethod(\n")
    append("      Class<?> owner, String name, Class<?>... parameterTypes) {\n")
    append("    try {\n")
    append("      return owner.getDeclaredMethod(name, parameterTypes);\n")
    append("    } catch (Exception e) {\n")
    append("      throw new ExceptionInInitializerError(e);\n")
    append("    }\n")
    append("  }\n\n")
  }

  private fun adapt(expression: String, from: JvmType, to: JvmType): String {
    if (from == to) return expression
    require(!from.primitive && !to.primitive) { "Incompatible generated value-class carriers" }
    return "(${to.sourceName}) $expression"
  }

  private fun valueOperationType(type: JvmType): String =
    when (type.descriptor) {
      "Z" -> "KotlinBooleanValueClassOperations"
      "B" -> "KotlinByteValueClassOperations"
      "S" -> "KotlinShortValueClassOperations"
      "I" -> "KotlinIntValueClassOperations"
      "J" -> "KotlinLongValueClassOperations"
      "F" -> "KotlinFloatValueClassOperations"
      "D" -> "KotlinDoubleValueClassOperations"
      "C" -> "KotlinCharValueClassOperations"
      else -> "KotlinReferenceValueClassOperations"
    }

  private fun valueOperationName(type: JvmType): String =
    when (type.descriptor) {
      "Z" -> "Boolean"
      "B" -> "Byte"
      "S" -> "Short"
      "I" -> "Int"
      "J" -> "Long"
      "F" -> "Float"
      "D" -> "Double"
      "C" -> "Char"
      else -> "Value"
    }

  private fun sourceName(binaryName: String): String = binaryName.replace('$', '.')

  private fun classDescriptor(binaryName: String): String = "L${binaryName.replace('.', '/')};"

  private fun StringBuilder.appendCreator(model: JsonModel, creator: JsonCreator) {
    append("  @Override\n")
    append("  public String[] creatorParameterNames() {\n")
    append("    return new String[] {")
    creator.parameterNames.joinTo(this, ", ") { "\"${escapeJava(it)}\"" }
    append("};\n")
    append("  }\n\n")
    if (creator.factory) {
      append("  @Override\n")
      append("  public String creatorFactoryName() {\n")
      append("    return \"${escapeJava(creator.invocationName)}\";\n")
      append("  }\n\n")
    }
    append("  @Override\n")
    append("  public Class<?>[] creatorParameterTypes() {\n")
    append("    return new Class<?>[] {")
    creator.parameterTypes.joinTo(this, ", ") { it.classLiteral }
    append("};\n")
    append("  }\n\n")
    append("  @Override\n")
    append("  public ${model.targetSourceName} newInstance(Object[] arguments) {\n")
    creator.parameterTypes.indices.forEach { index ->
      append("    boolean missing$index = ")
      append("org.apache.fory.json.meta.JsonCreatorInfo.isMissing(arguments[$index]);\n")
      if (!creator.optional[index]) {
        append("    if (missing$index) {\n")
        append("      throw new org.apache.fory.json.ForyJsonException(")
        append("\"Missing required JSON constructor property ")
        append(escapeJava(creator.parameterNames[index]))
        append(" for ")
        append(escapeJava(model.targetBinaryName))
        append("\");\n")
        append("    }\n")
      }
    }
    if (creator.defaultDescriptor != null) {
      repeat(creator.maskCount) { append("    int mask$it = 0;\n") }
      creator.parameterTypes.indices.forEach { index ->
        if (creator.optional[index]) {
          append("    if (missing$index) mask${index ushr 5} |= ${1 shl (index and 31)};\n")
        }
      }
    }
    append("    try {\n")
    if (creator.defaultDescriptor != null) {
      append("      if ((")
      repeat(creator.maskCount) { index ->
        if (index != 0) append(" | ")
        append("mask$index")
      }
      append(") == 0) {\n")
      append("        return ${model.operationSimpleName}.createFull(")
      creator.parameterTypes.indices.joinTo(this, ", ") { index ->
        creator.parameterTypes[index].argumentExpression("arguments[$index]")
      }
      append(");\n")
      append("      }\n")
      append("      return ${model.operationSimpleName}.createDefault(")
      val arguments = ArrayList<String>(creator.parameterTypes.size + creator.maskCount)
      creator.parameterTypes.indices.forEach { index ->
        val value = creator.parameterTypes[index].argumentExpression("arguments[$index]")
        arguments +=
          if (creator.optional[index]) {
            "missing$index ? ${creator.parameterTypes[index].defaultExpression} : $value"
          } else {
            value
          }
      }
      repeat(creator.maskCount) { arguments += "mask$it" }
      arguments.joinTo(this, ", ")
      append(");\n")
    } else {
      append("      return ${model.operationSimpleName}.createFull(")
      creator.parameterTypes.indices.joinTo(this, ", ") { index ->
        creator.parameterTypes[index].argumentExpression("arguments[$index]")
      }
      append(");\n")
    }
    append("    } catch (Throwable throwable) {\n")
    append("      throw creatorFailure(throwable);\n")
    append("    }\n")
    append("  }\n\n")
  }

  private fun StringBuilder.appendAnySetter(model: JsonModel, setter: JvmAnySetter) {
    val descriptor = parseMethodDescriptor(setter.descriptor)
    val owner = JvmType("L${setter.ownerBinaryName.replace('.', '/')};").sourceName
    val valueType = descriptor.parameters[1]
    append("  @Override\n")
    append("  public org.apache.fory.json.meta.JsonAnySetterAccessor anySetterAccessor() {\n")
    append("    return new AnySetterAccessor();\n")
    append("  }\n\n")
    append("  private static final class AnySetterAccessor\n")
    append("      extends org.apache.fory.json.meta.JsonAnySetterAccessor {\n")
    append("    private static final java.lang.reflect.Method MEMBER =\n")
    append("        declaredMethod($owner.class, \"${escapeJava(setter.name)}\", ")
    append("String.class, ${valueType.classLiteral});\n\n")
    append("    @Override\n")
    append("    public java.lang.reflect.Method setter() {\n")
    append("      return MEMBER;\n")
    append("    }\n\n")
    append("    @Override\n")
    append("    public void put(Object target, String name, Object value) {\n")
    append("      try {\n")
    append("        ${model.operationSimpleName}.setAny(")
    append("(${model.targetSourceName}) target, name, ${valueType.argumentExpression("value")});\n")
    append("      } catch (Throwable throwable) {\n")
    append("        throw accessException(MEMBER, throwable);\n")
    append("      }\n")
    append("    }\n")
    append("  }\n\n")
  }

  private fun StringBuilder.appendValidators(model: JsonModel) {
    model.validators.forEachIndexed { index, validator ->
      append("  private static final java.lang.reflect.Method VALIDATOR_$index =\n")
      append("      validatorMethod(${model.targetSourceName}.class, ")
      append("\"${escapeJava(validator.name)}\");\n")
    }
    append('\n')
    append("  @Override\n")
    append("  public java.lang.reflect.Method[] validatorMethods() {\n")
    append("    return new java.lang.reflect.Method[] {")
    model.validators.indices.joinTo(this, ", ") { "VALIDATOR_$it" }
    append("};\n")
    append("  }\n\n")
    append("  @Override\n")
    append("  public void invokeValidators(Object target) {\n")
    model.validators.indices.forEach { index ->
      append("    try {\n")
      append("      ${model.operationSimpleName}.validate_$index(")
      append("(${model.targetSourceName}) target);\n")
      append("    } catch (Throwable throwable) {\n")
      append("      throw validatorFailure(${model.targetSourceName}.class, ")
      append("VALIDATOR_$index, throwable);\n")
      append("    }\n")
    }
    append("  }\n\n")
  }

  private fun StringBuilder.appendReflectionHelpers() {
    append(
      "  private static java.lang.reflect.Field declaredField(Class<?> owner, String name) {\n"
    )
    append("    try {\n")
    append("      return owner.getDeclaredField(name);\n")
    append("    } catch (Exception e) {\n")
    append("      throw new ExceptionInInitializerError(e);\n")
    append("    }\n")
    append("  }\n\n")
    append("  private static java.lang.reflect.Method declaredMethod(\n")
    append("      Class<?> owner, String name, Class<?>... parameterTypes) {\n")
    append("    try {\n")
    append("      return owner.getDeclaredMethod(name, parameterTypes);\n")
    append("    } catch (Exception e) {\n")
    append("      throw new ExceptionInInitializerError(e);\n")
    append("    }\n")
    append("  }\n\n")
  }

  private fun StringBuilder.appendAccessor(model: JsonModel, index: Int, member: JvmMember) {
    val owner = JvmType("L${member.ownerBinaryName.replace('.', '/')};").sourceName
    append("  private static final class Accessor$index\n")
    append("      extends org.apache.fory.json.meta.JsonFieldAccessor {\n")
    when (member.kind) {
      MemberKind.FIELD -> {
        append("    private static final java.lang.reflect.Field MEMBER =\n")
        append("        declaredField($owner.class, \"${escapeJava(member.name)}\");\n\n")
        append("    @Override\n")
        append("    public java.lang.reflect.Field field() {\n")
        append("      return MEMBER;\n")
        append("    }\n\n")
        val type = JvmType(member.descriptor)
        appendGetter(model, index, type, false)
        if (member.writable) appendSetter(model, index, type, false)
      }
      MemberKind.GETTER -> {
        val descriptor = parseMethodDescriptor(member.descriptor)
        val type = JvmType(descriptor.result)
        append("    private static final java.lang.reflect.Method MEMBER =\n")
        append("        declaredMethod($owner.class, \"${escapeJava(member.name)}\");\n\n")
        append("    @Override\n")
        append("    public java.lang.reflect.Method getter() {\n")
        append("      return MEMBER;\n")
        append("    }\n\n")
        appendGetter(model, index, type, true)
      }
      MemberKind.SETTER -> {
        val descriptor = parseMethodDescriptor(member.descriptor)
        val type = descriptor.parameters.single()
        append("    private static final java.lang.reflect.Method MEMBER =\n")
        append("        declaredMethod($owner.class, \"${escapeJava(member.name)}\", ")
        append("${type.classLiteral});\n\n")
        append("    @Override\n")
        append("    public java.lang.reflect.Method setter() {\n")
        append("      return MEMBER;\n")
        append("    }\n\n")
        appendSetter(model, index, type, true)
      }
    }
    append("  }\n\n")
  }

  private fun StringBuilder.appendGetter(
    model: JsonModel,
    index: Int,
    type: JvmType,
    catchesFailure: Boolean,
  ) {
    val primitiveMethod = primitiveMethod(type)
    val returnType = if (primitiveMethod == null) "Object" else type.sourceName
    val method = if (primitiveMethod == null) "getObject" else "get$primitiveMethod"
    append("    @Override\n")
    append("    public $returnType $method(Object target) {\n")
    if (catchesFailure) append("      try {\n")
    val indent = if (catchesFailure) "        " else "      "
    append(indent)
    append("return ${model.operationSimpleName}.get_$index((${model.targetSourceName}) target);\n")
    if (catchesFailure) {
      append("      } catch (Throwable throwable) {\n")
      append("        throw accessException(MEMBER, throwable);\n")
      append("      }\n")
    }
    append("    }\n\n")
    if (primitiveMethod != null) {
      append("    @Override\n")
      append("    public Object getObject(Object target) {\n")
      append("      return $method(target);\n")
      append("    }\n\n")
    }
  }

  private fun StringBuilder.appendSetter(
    model: JsonModel,
    index: Int,
    type: JvmType,
    catchesFailure: Boolean,
  ) {
    val primitiveMethod = primitiveMethod(type)
    val parameterType = if (primitiveMethod == null) "Object" else type.sourceName
    val method = if (primitiveMethod == null) "putObject" else "put$primitiveMethod"
    val value = if (primitiveMethod == null) "(${type.sourceName}) value" else "value"
    append("    @Override\n")
    append("    public void $method(Object target, $parameterType value) {\n")
    if (catchesFailure) append("      try {\n")
    val indent = if (catchesFailure) "        " else "      "
    append(indent)
    append("${model.operationSimpleName}.set_$index((${model.targetSourceName}) target, $value);\n")
    if (catchesFailure) {
      append("      } catch (Throwable throwable) {\n")
      append("        throw accessException(MEMBER, throwable);\n")
      append("      }\n")
    }
    append("    }\n\n")
    if (primitiveMethod != null) {
      append("    @Override\n")
      append("    public void putObject(Object target, Object value) {\n")
      append("      $method(target, ${type.argumentExpression("value")});\n")
      append("    }\n\n")
    }
  }

  private fun primitiveMethod(type: JvmType): String? =
    when (type.descriptor) {
      "Z" -> "Boolean"
      "B" -> "Byte"
      "S" -> "Short"
      "I" -> "Int"
      "J" -> "Long"
      "F" -> "Float"
      "D" -> "Double"
      "C" -> "Char"
      else -> null
    }

  private fun escapeJava(value: String): String =
    buildString(value.length) {
      value.forEach { character ->
        when (character) {
          '\b' -> append("\\b")
          '\t' -> append("\\t")
          '\n' -> append("\\n")
          '\u000c' -> append("\\f")
          '\r' -> append("\\r")
          '"' -> append("\\\"")
          '\\' -> append("\\\\")
          else ->
            if (character.isISOControl() || character == '\u2028' || character == '\u2029') {
              append("\\u")
              append(character.code.toString(16).padStart(4, '0'))
            } else {
              append(character)
            }
        }
      }
    }
}
