/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.fory.serializer.scala;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.Arrays;
import org.apache.fory.collection.LongMap;
import org.apache.fory.config.Config;
import org.apache.fory.context.ReadContext;
import org.apache.fory.context.WriteContext;
import org.apache.fory.scala.ForyScalaEnum;
import org.apache.fory.serializer.ImmutableSerializer;
import org.apache.fory.serializer.Shareable;
import org.apache.fory.util.Preconditions;

/** Serializer for Scala 3 enums generated by the Fory Scala schema IDL target. */
@SuppressWarnings({"unchecked", "rawtypes"})
public final class ScalaEnumSerializer extends ImmutableSerializer<Object> implements Shareable {
  private static final int MAX_ENUM_ID_ARRAY_SIZE = 2048;

  private final Config config;
  private final Object[] enumConstants;
  private final Object[] enumConstantByTagArray;
  private final LongMap<Object> enumConstantByTagMap;

  public ScalaEnumSerializer(org.apache.fory.resolver.TypeResolver resolver, Class<?> cls) {
    super(resolver.getConfig(), (Class<Object>) cls, false);
    config = resolver.getConfig();
    Preconditions.checkArgument(
        ForyScalaEnum.class.isAssignableFrom(cls),
        "Scala enum %s must implement %s",
        cls,
        ForyScalaEnum.class.getName());
    enumConstants = loadValues(cls);
    LongMap<Object> constantsByTag = new LongMap<>(enumConstants.length);
    int maxTag = 0;
    for (Object enumConstant : enumConstants) {
      int tag = ((ForyScalaEnum) enumConstant).getForyId();
      Object previous = constantsByTag.put(tag, enumConstant);
      Preconditions.checkArgument(
          previous == null,
          "Scala enum %s reuses Fory enum id %s for %s and %s",
          cls.getName(),
          tag,
          previous,
          enumConstant);
      if (tag > maxTag) {
        maxTag = tag;
      }
    }
    if (maxTag < MAX_ENUM_ID_ARRAY_SIZE) {
      enumConstantByTagArray = new Object[maxTag + 1];
      constantsByTag.forEach((tag, value) -> enumConstantByTagArray[tag.intValue()] = value);
      enumConstantByTagMap = null;
    } else {
      enumConstantByTagArray = null;
      enumConstantByTagMap = constantsByTag;
    }
  }

  @Override
  public void write(WriteContext writeContext, Object value) {
    writeContext.getBuffer().writeVarUInt32Small7(((ForyScalaEnum) value).getForyId());
  }

  @Override
  public Object read(ReadContext readContext) {
    int tag = readContext.getBuffer().readVarUInt32Small7();
    Object value = null;
    if (enumConstantByTagArray != null && tag < enumConstantByTagArray.length) {
      value = enumConstantByTagArray[tag];
    } else if (enumConstantByTagMap != null) {
      value = enumConstantByTagMap.get(tag);
    }
    if (value != null) {
      return value;
    }
    return handleUnknownEnumValue(tag);
  }

  private Object handleUnknownEnumValue(int tag) {
    switch (config.getUnknownEnumValueStrategy()) {
      case RETURN_NULL:
        return null;
      case RETURN_FIRST_VARIANT:
        return enumConstants[0];
      case RETURN_LAST_VARIANT:
        return enumConstants[enumConstants.length - 1];
      default:
        throw new IllegalArgumentException(
            String.format("Scala enum tag %s not in %s", tag, Arrays.toString(enumConstants)));
    }
  }

  private static Object[] loadValues(Class<?> cls) {
    try {
      Method values = cls.getMethod("values");
      Object result = values.invoke(null);
      Preconditions.checkArgument(
          result instanceof Object[], "Scala enum %s values() did not return an array", cls);
      return (Object[]) result;
    } catch (NoSuchMethodException | IllegalAccessException | InvocationTargetException e) {
      throw new IllegalArgumentException("Failed to load Scala enum values for " + cls.getName(), e);
    }
  }
}
