/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.fory.serializer;

import java.util.List;
import org.apache.fory.annotation.Internal;
import org.apache.fory.meta.TypeDef;
import org.apache.fory.resolver.TypeResolver;
import org.apache.fory.type.Descriptor;

/**
 * Factory for statically shaped struct serializers whose implementation is generated by a non-Java
 * compiler.
 *
 * <p>Named generated serializer classes are still discovered by {@link
 * org.apache.fory.resolver.StaticGeneratedSerializerRegistry}. This factory path is for language
 * frontends such as Scala 3 macro derivation where the serializer code is emitted at the typeclass
 * call site rather than as a separately named JVM class.
 */
@Internal
public interface StaticGeneratedStructSerializerFactory<T> {
  /** Descriptor metadata generated from the source-language type model. */
  List<Descriptor> getGeneratedDescriptors();

  /**
   * Create a serializer for {@code type}.
   *
   * @param typeDef remote TypeDef for compatible reads, or {@code null} for local schema reads.
   */
  StaticGeneratedStructSerializer<T> newSerializer(
      TypeResolver typeResolver, Class<?> type, TypeDef typeDef);
}
